set mouse=
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Bundle 'chase/vim-ansible-yaml'
Plugin 'jszakmeister/vim-togglecursor'

call vundle#end()            " required
filetype plugin indent on    " required

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal



syntax on
set tabstop=4
set softtabstop=4
set expandtab
filetype indent on
set wildmenu
set showmatch
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=syntax
set number
"let g:powerline_pycmd
"let g:powerline_pyeval
set rtp+=/usr/lib/python3.4/site-packages/powerline/bindings/vim
set laststatus=2
set t_Co=256
set cul
colorscheme molokai
let g:rehash256=1
