# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/Scripts:$PATH
export PATH=$HOME/Stuff/pebble/PebbleSDK-2.8.1/bin:$PATH
export PATH=$HOME/.gem/ruby/2.3.0/bin:$PATH
export PATH=/usr/lib/jvm/java-8-openjdk/bin:$PATH

eval $(dircolors ~/.dircolors)
eval $(dircolors /usr/share/dircolors/dircolors.256dark)

source /usr/bin/virtualenvwrapper.sh
export WORKON_HOME=~/Envs

export BROWSER
export DEFAULT_USER=freddy

xrdb ~/.Xresources

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="bira"
#ZSH_THEME="agnoster"
#ZSH_THEME="amuse"
#ZSH_THEME="bullet-train"


#ZSH_THEME="zsh2000"
export ZSH_2000_DEFAULT_USER='freddy'
export ZSH_2000_DISABLE_RVM='true'

ZSH_THEME="powerlevel9k/powerlevel9k"
#ZSH_THEME="ownPowerlevel/ownPowerlevel"
POWERLEVEL9k_MODE='awesome-patched'
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(rbenv virtualenv longstatus time)


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras battery colorize command-not-found common-aliases gitignore cp archlinux history history-substring-search gnu-utils pip python ssh-agent sudo systemd vim-interaction ruby rake bundler rails rbenv zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=/home/freddy/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export EDITOR=vim
alias wlan='sudo systemctl restart netctl-auto@wlp4s0.service'
alias grep="/usr/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS
source /usr/share/autoenv-git/activate.sh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
