#!/bin/sh
xmodmap ~/.xmodmap

output=$(xinput list-props 'SynPS/2 Synaptics TouchPad' | grep 'Device Enabled' | grep 0)
if [ "$output" == "" ]; then
        $(xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Device Enabled' 0)
        echo "Disabled touchpad"
else 
        $(xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Device Enabled' 1)
        echo "Enabled touchpad"
fi
