#!/bin/sh
xmodmap ~/.xmodmap

#$device_name = 'SynPS/2 Synaptics TouchPad'
device_name='Synaptics TM3053-003'

output=$(xinput list-props "$device_name" | grep 'Device Enabled' | grep 0)
if [ "$output" == "" ]; then
        $(xinput set-prop "$device_name" 'Device Enabled' 0)
        echo "Disabled touchpad"
else
        $(xinput set-prop "$device_name" 'Device Enabled' 1)
          echo "Enabled touchpad"
fi
